package org.example.incident;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2014-10-06T12:34:08.045+02:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://www.example.org/incident/", name = "IncidentService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IncidentService {

    @WebResult(name = "NewPart", targetNamespace = "", partName = "NewPart")
    @WebMethod(operationName = "RegisterIncident", action = "http://www.example.org/incident/RegisterIncident")
    public RegisterIncidentResponseType registerIncident(
        @WebParam(partName = "name", name = "name", targetNamespace = "")
        RegisterIncidentRequestType name
    );
}
